Hw1-1 Repo orgnarization
Tozarin/formal-lang-course pull request #1
Opened 2023-09-13 18:03 UTC by Tozarin

2023-09-15 19:12 UTC, vadyushkins requested changes

2023-09-15 19:12 UTC, vadyushkins commented on project/utils/graph_utils.py
> +from collections import namedtuple
https://peps.python.org/pep-0008/#imports

2023-09-15 19:12 UTC, vadyushkins commented on tests/test_graph_utils.py
> +from networkx import algorithms, is_isomorphic
https://peps.python.org/pep-0008/#imports

2023-09-15 19:34 UTC, Tozarin commented on project/utils/graph_utils.py
> +from collections import namedtuple
Я вроде поправил в соответствии с гайдлайном

2023-09-20 07:11 UTC, vadyushkins approved these changes

2023-09-20 10:11 UTC, merged